language: bash
services: docker
before_install:
  - cd Project_Using_Springboot_Docker_Aws\ Docker/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push ditto07/mysql-rest-with-spring-boot-udemy;
    docker push ditto07/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false
